# Generated by Django 5.2.2 on 2025-06-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Social')),
                ('profession', models.CharField(max_length=100, verbose_name='Profissão')),
                ('address', models.TextField(verbose_name='Endereço')),
                ('contact', models.CharField(max_length=100, verbose_name='Contato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
                'ordering': ['name'],
            },
        ),
    ]
