# Generated by Django 5.2.2 on 2025-06-07 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professional',
            options={'ordering': ['preferred_name'], 'verbose_name': 'Profissional', 'verbose_name_plural': 'Profissionais'},
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='name',
            new_name='preferred_name',
        ),
    ]
