# Generated by Django 5.2.2 on 2025-06-08 06:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_alter_professional_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='contact',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='O número de telefone deve conter 11 dígitos numéricos.', regex='^\\d{11}$')], verbose_name='Contato'),
        ),
    ]
