# Generated by Django 5.2.2 on 2025-06-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professionals", "0004_alter_professional_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="professional",
            name="specialty",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Especialidade"
            ),
        ),
    ]
